---
imagebuilder: "/home/nick/openwrt/bin/targets/ipq40xx/mikrotik/openwrt-imagebuilder-ipq40xx-mikrotik.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
imagebuilder_disable_signature_check: true
target: ipq40xx/mikrotik
override_target: "mikrotik_sxtsq-5-ac"

model__packages__to_merge:
  - "-kmod-ath10k-ct -ath10k-firmware-qca4019-ct"
  - "kmod-ath10k ath10k-firmware-qca4019"

dsa_ports:
  - lan

wireless_devices:
  - name: 11a_standard
    hwmode: 11a
    path: platform/soc/a800000.wifi
    ifname_hint: wlan5
