---
imagebuilder: "https://downloads.openwrt.org/releases/21.02-SNAPSHOT/targets/ath79/generic/openwrt-imagebuilder-21.02-SNAPSHOT-ath79-generic.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
imagebuilder_disable_signature_check: true
override_target: "tplink_cpe210-v1"
target: ath79/generic

int_port: eth1

wireless_devices:
  - name: 11g_standard
    hwmode: 11g
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
