---
imagebuilder: "https://downloads.openwrt.org/releases/21.02-SNAPSHOT/targets/ath79/generic/openwrt-imagebuilder-21.02-SNAPSHOT-ath79-generic.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
imagebuilder_disable_signature_check: true

int_port: eth0

wireless_devices:
  - name: 11g_standard
    hwmode: 11g
    path: ToDo
    ifname_hint: wlan2
