---
imagebuilder: "https://downloads.openwrt.org/releases/21.02.1/targets/ath79/mikrotik/openwrt-imagebuilder-21.02.1-ath79-mikrotik.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
imagebuilder_disable_signature_check: true
override_target: "mikrotik_routerboard-wap-g-5hact2hnd"
target: ath79/mikrotik

int_port: eth0

wireless_devices:
  - name: 11g_standard
    hwmode: 11g
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
  - name: 11a_standard
    hwmode: 11a
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5
