---
imagebuilder: "/home/spolack/git/openwrt/bin/targets/ipq40xx/generic/openwrt-imagebuilder-ipq40xx-generic.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
imagebuilder_disable_signature_check: true
target: ipq40xx/generic
override_target: "avm_fritzbox-7530"

model__packages__to_merge:
  - "-kmod-ath10k-ct -ath10k-firmware-qca4019-ct"
  - "kmod-ath10k ath10k-firmware-qca4019"

dsa_ports:
  - lan1
  - lan2
  - lan3
  - lan4

wireless_devices:
  - name: 11a_standard
    hwmode: 11a
    path: platform/soc/a800000.wifi
    ifname_hint: wlan5
  - name: 11g_standard
    hwmode: 11g
    path: platform/soc/a000000.wifi
    ifname_hint: wlan2
