---
- name: "Add irqbalance if multicore"
  set_fact:
    packages: "{{ packages + ['irqbalance'] }}"
  when:
    - multicore|default(false)|bool == true

- name: "Add airos-dfs-reset if configured"
  set_fact:
    packages: "{{ packages + ['airos-dfs-reset'] }}"
  when:
    - airos_dfs_reset|default([])|length > 0
    - role == 'corerouter'

- name: "Add zram-swap on low mem and big flash"
  set_fact:
    packages: "{{ packages + ['zram-swap'] }}"
  when:
    - low_mem | default(false)
    - not (low_flash | default(false))

- name: "Remove packages on low mem and low flash"
  set_fact:
    packages: "{{ packages + ['-' + item] }}"
  when: low_mem | default(false) or low_flash | default(false)
  loop:
    - luci-ssl
    - kmod-usb2
    - kmod-usb-ehci
    - kmod-usb-ohci
    - kmod-phy-ath79-usb
    - kmod-usb-core
    - kmod-nls-base
    - iptables
    - ip6tables
    - kmod-nf-ipt
    - kmod-ipt-core
    - kmod-ipt-offload
    - -tcpdump
    - tcpdump-mini

- name: "Add ip-bridge if dsa target"
  set_fact:
    packages: "{{ packages + ['ip-bridge'] }}"
  when:
    - dsa_ports is defined
